# Radarr Docker Container Setup with Optimized Volume Structure
# This script uses the recommended single common volume approach to enable fast moves and hard links

# IMPORTANT: Update the host paths below to match your actual directories
$hostDataPath = "C:\docker\data"  # Change this to your preferred host path
$hostConfigPath = "C:\docker\radarr\config"  # Change this to your preferred config path

# Create a custom Docker network for container communication
Write-Host "Creating Docker network 'media-stack'..."
cmd /c "docker network create media-stack 2>nul || echo Network already exists"

# Run Radarr container on the custom network
cmd /c "docker run --name radarr --restart unless-stopped --network media-stack -d -p 7878:7878 -v ${hostConfigPath}:/config -v ${hostDataPath}:/data ghcr.io/hotio/radarr"

Write-Host "=== RADARR DOCKER SETUP ==="
Write-Host "Radarr container should now be running. Access it at http://localhost:7878"
Write-Host ""
Write-Host "=== IMPORTANT: DIRECTORY STRUCTURE ==="
Write-Host "Make sure your host directory structure looks like this:"
Write-Host "  $hostDataPath\"
Write-Host "    Movies\           (for your movie library)"
Write-Host "    downloads\"
Write-Host "      torrents\       (for torrent downloads)"
Write-Host "      usenet\         (for usenet downloads)"
Write-Host ""
Write-Host "=== RADARR CONFIGURATION ==="
Write-Host "In Radarr settings, configure your paths as:"
Write-Host "  • Movies: /data/Movies"
Write-Host "  • Download folders: /data/downloads/torrents and/or /data/downloads/usenet"
Write-Host ""
Write-Host "=== DOWNLOAD CLIENT SETUP ==="
Write-Host "IMPORTANT: When configuring download clients in Radarr, use these hostnames:"
Write-Host "  • qBittorrent host: qbittorrent"
Write-Host "  • SABnzbd host: sabnzbd"
Write-Host "  • Port numbers remain the same (8080 for qBit, 8080 for SAB)"
Write-Host ""
Write-Host "=== COMPLETE MEDIA STACK SETUP ==="
Write-Host "TV SHOWS: Set up Sonarr for TV series management!"
Write-Host "Run: .\run-sonarr.ps1"
Write-Host "Sonarr manages TV shows just like Radarr manages movies."
Write-Host ""
Write-Host "INDEXERS: Set up Prowlarr as your indexer manager!"
Write-Host "Run: .\run-prowlarr.ps1"
Write-Host "Prowlarr will automatically manage and sync indexers to both Radarr and Sonarr."
Write-Host ""
Write-Host "SUBTITLES: Set up Bazarr for automatic subtitle downloads!"
Write-Host "Run: .\run-bazarr.ps1"
Write-Host "Bazarr will automatically download subtitles for both movies and TV shows."
Write-Host ""
Write-Host "=== DOWNLOAD CLIENT EXAMPLES ==="
Write-Host "Run these commands to start download clients on the same network:"
Write-Host ""
Write-Host "qBittorrent:"
$qbitCommand = "docker run --name qbittorrent --network media-stack -d -p 8080:8080 -v `"${hostConfigPath}-qbit:/config`" -v `"${hostDataPath}:/data`" lscr.io/linuxserver/qbittorrent"
Write-Host "  $qbitCommand"
Write-Host ""
Write-Host "SABnzbd:"
$sabCommand = "docker run --name sabnzbd --network media-stack -d -p 8081:8080 -v `"${hostConfigPath}-sab:/config`" -v `"${hostDataPath}:/data`" lscr.io/linuxserver/sabnzbd"
Write-Host "  $sabCommand"
Write-Host ""
Write-Host "=== NETWORK CONFIGURATION ==="
Write-Host "All containers are now on the 'media-stack' network and can communicate!"
Write-Host "This ensures fast moves, hard links, AND container communication work properly!" 