# Sonarr Docker Container Setup with Optimized Volume Structure
# This script uses the recommended single common volume approach to enable fast moves and hard links for TV Shows

# IMPORTANT: Update the host paths below to match your actual directories
$hostDataPath = "C:\docker\data"  # Should match your other *arr apps data path
$hostConfigPath = "C:\docker\sonarr\config"  # Change this to your preferred config path

# Create a custom Docker network for container communication (if it doesn't exist)
Write-Host "Creating Docker network 'media-stack'..."
cmd /c "docker network create media-stack 2>nul || echo Network already exists"

# Run Sonarr container on the custom network
cmd /c "docker run --name sonarr --restart unless-stopped --network media-stack -d -p 8989:8989 -v ${hostConfigPath}:/config -v ${hostDataPath}:/data ghcr.io/hotio/sonarr"

Write-Host "=== SONARR DOCKER SETUP ==="
Write-Host "Sonarr container should now be running. Access it at http://localhost:8989"
Write-Host ""
Write-Host "=== IMPORTANT: DIRECTORY STRUCTURE ==="
Write-Host "Make sure your host directory structure looks like this:"
Write-Host "  $hostDataPath\"
Write-Host "    TV Shows\         (for your TV series library)"
Write-Host "    Movies\           (for your movie library - used by Radarr)"
Write-Host "    downloads\"
Write-Host "      torrents\       (for torrent downloads)"
Write-Host "      usenet\         (for usenet downloads)"
Write-Host ""
Write-Host "=== SONARR CONFIGURATION ==="
Write-Host "In Sonarr settings, configure your paths as:"
Write-Host "  • TV Shows: /data/TV Shows"
Write-Host "  • Download folders: /data/downloads/torrents and/or /data/downloads/usenet"
Write-Host ""
Write-Host "=== PROWLARR INTEGRATION ==="
Write-Host "IMPORTANT: Add Sonarr to your existing Prowlarr setup!"
Write-Host "In Prowlarr (http://localhost:9696):"
Write-Host "1. Go to Settings > Apps"
Write-Host "2. Click '+' to add Sonarr"
Write-Host "3. Configure with these settings:"
Write-Host "   • Name: Sonarr"
Write-Host "   • Sync Level: Full Sync"
Write-Host "   • Server: http://sonarr:8989"
Write-Host "   • API Key: [Get from Sonarr Settings > General]"
Write-Host ""
Write-Host "=== BAZARR INTEGRATION ==="
Write-Host "IMPORTANT: Add Sonarr to your existing Bazarr setup for TV subtitles!"
Write-Host "In Bazarr (http://localhost:6767):"
Write-Host "1. Go to Settings > Sonarr"
Write-Host "2. Configure with these settings:"
Write-Host "   • Enable: Yes"
Write-Host "   • Address: http://sonarr:8989"
Write-Host "   • API Key: [Get from Sonarr Settings > General]"
Write-Host "   • Series Path: /data/TV Shows"
Write-Host ""
Write-Host "=== DOWNLOAD CLIENT SETUP ==="
Write-Host "IMPORTANT: When configuring download clients in Sonarr, use these hostnames:"
Write-Host "  • qBittorrent host: qbittorrent"
Write-Host "  • SABnzbd host: sabnzbd"
Write-Host "  • Port numbers remain the same (8080 for qBit, 8080 for SAB)"
Write-Host ""
Write-Host "=== QUALITY PROFILES ==="
Write-Host "Recommended quality profiles for TV shows:"
Write-Host "• HD-720p/1080p (for most series)"
Write-Host "• WEB-DL preferred over HDTV"
Write-Host "• Enable 'Upgrade Until Custom Format Score' for better quality"
Write-Host ""
Write-Host "=== SERIES TYPES ==="
Write-Host "Sonarr supports different series types:"
Write-Host "• Standard: Most TV shows (episodes air weekly)"
Write-Host "• Daily: Talk shows, news programs"
Write-Host "• Anime: Japanese animation (different naming conventions)"
Write-Host ""
Write-Host "=== GET SONARR API KEY ==="
Write-Host "To get Sonarr API key for Prowlarr/Bazarr integration:"
Write-Host "1. Go to http://localhost:8989"
Write-Host "2. Settings > General > Security"
Write-Host "3. Copy the API Key value"
Write-Host "4. Use this key when adding Sonarr to Prowlarr and Bazarr"
Write-Host ""
Write-Host "=== NETWORK CONFIGURATION ==="
Write-Host "All containers are on the 'media-stack' network and can communicate!"
Write-Host "Use container names as hostnames:"
Write-Host "• radarr:7878 (movies)"
Write-Host "• sonarr:8989 (TV shows)"
Write-Host "• prowlarr:9696 (indexers)"
Write-Host "• bazarr:6767 (subtitles)"
Write-Host "• qbittorrent:8080 (downloads)"
Write-Host ""
Write-Host "=== COMPLETE MEDIA STACK ==="
Write-Host "Your full media automation stack:"
Write-Host "• Radarr (Movies): http://localhost:7878"
Write-Host "• Sonarr (TV Shows): http://localhost:8989"
Write-Host "• Prowlarr (Indexers): http://localhost:9696"
Write-Host "• Bazarr (Subtitles): http://localhost:6767"
Write-Host "• qBittorrent (Downloads): http://localhost:8080"
Write-Host ""
Write-Host "=== SETUP CHECKLIST ==="
Write-Host "□ Configure quality profiles in Sonarr"
Write-Host "□ Add Sonarr to Prowlarr (Settings > Apps)"
Write-Host "□ Add Sonarr to Bazarr (Settings > Sonarr)"
Write-Host "□ Configure download client in Sonarr"
Write-Host "□ Test indexer searches"
Write-Host "□ Add your first TV series!" 