# Bazarr Docker Container Setup - Subtitle Management for Radarr
# This script sets up Bazarr to automatically download subtitles for movies managed by Radarr

# IMPORTANT: Update the host paths below to match your actual directories
$hostDataPath = "C:\docker\data"  # Should match your Radarr data path
$hostConfigPath = "C:\docker\bazarr\config"  # Change this to your preferred config path

# Create a custom Docker network for container communication (if it doesn't exist)
Write-Host "Creating Docker network 'media-stack'..."
cmd /c "docker network create media-stack 2>nul || echo Network already exists"

# Run Bazarr container on the custom network
cmd /c "docker run --name bazarr --restart unless-stopped --network media-stack -d -p 6767:6767 -v ${hostConfigPath}:/config -v ${hostDataPath}:/data ghcr.io/hotio/bazarr"

Write-Host "=== BAZARR DOCKER SETUP ==="
Write-Host "Bazarr container should now be running. Access it at http://localhost:6767"
Write-Host ""
Write-Host "=== BAZARR CONFIGURATION ==="
Write-Host "1. Access Bazarr at http://localhost:6767"
Write-Host "2. Complete the initial setup wizard"
Write-Host "3. Connect to your media libraries:"
Write-Host "   • Settings > Radarr (for movies)"
Write-Host "   • Settings > Sonarr (for TV shows) - if you have it"
Write-Host ""
Write-Host "=== RADARR INTEGRATION (MOVIES) ==="
Write-Host "In Bazarr Settings > Radarr, configure:"
Write-Host "   • Enable: Yes"
Write-Host "   • Address: http://radarr:7878"
Write-Host "   • API Key: [Get this from Radarr Settings > General]"
Write-Host "   • Movie Path: /data/Movies"
Write-Host "   • Test the connection!"
Write-Host ""
Write-Host "=== SONARR INTEGRATION (TV SHOWS) ==="
Write-Host "In Bazarr Settings > Sonarr, configure (if you have Sonarr):"
Write-Host "   • Enable: Yes"
Write-Host "   • Address: http://sonarr:8989"
Write-Host "   • API Key: [Get this from Sonarr Settings > General]"
Write-Host "   • Series Path: /data/TV Shows"
Write-Host "   • Test the connection!"
Write-Host ""
Write-Host "=== SUBTITLE PROVIDERS ==="
Write-Host "Popular free subtitle providers to add:"
Write-Host "   • OpenSubtitles (requires free account)"
Write-Host "   • Subscene"
Write-Host "   • TVSubtitles"
Write-Host "   • Podnapisi"
Write-Host "   • BSPlayer"
Write-Host ""
Write-Host "=== LANGUAGE CONFIGURATION ==="
Write-Host "In Settings > Languages:"
Write-Host "1. Add your preferred subtitle languages"
Write-Host "2. Set language profiles for different quality preferences"
Write-Host "3. Configure series/movies type mapping"
Write-Host ""
Write-Host "=== AUTOMATIC SUBTITLES ==="
Write-Host "Bazarr will automatically:"
Write-Host "• Scan your movie library from Radarr"
Write-Host "• Scan your TV series library from Sonarr (if configured)"
Write-Host "• Download missing subtitles for both movies and TV shows"
Write-Host "• Monitor for new content and get subtitles"
Write-Host "• Upgrade subtitle quality when better ones are available"
Write-Host ""
Write-Host "=== DIRECTORY STRUCTURE ==="
Write-Host "Your directory structure should be:"
Write-Host "  $hostDataPath\"
Write-Host "    Movies\           (your movie library - shared with Radarr)"
Write-Host "      Movie1 (2023)\"
Write-Host "        movie1.mkv"
Write-Host "        movie1.srt    (subtitles will be placed here)"
Write-Host "    TV Shows\         (your TV series library - shared with Sonarr)"
Write-Host "      Series1 (2023)\"
Write-Host "        Season 01\"
Write-Host "          series1.s01e01.mkv"
Write-Host "          series1.s01e01.srt (subtitles will be placed here)"
Write-Host ""
Write-Host "=== SETUP CHECKLIST ==="
Write-Host "□ Complete Bazarr initial setup wizard"
Write-Host "□ Add subtitle providers in Settings > Providers"
Write-Host "□ Configure languages in Settings > Languages"
Write-Host "□ Connect to Radarr in Settings > Radarr (for movies)"
Write-Host "□ Connect to Sonarr in Settings > Sonarr (for TV shows)"
Write-Host "□ Test both connections"
Write-Host "□ Enable wanted subtitles monitoring"
Write-Host ""
Write-Host "=== GET API KEYS ==="
Write-Host "To get Radarr API key (for movies):"
Write-Host "1. Go to http://localhost:7878"
Write-Host "2. Settings > General > Security"
Write-Host "3. Copy the API Key value"
Write-Host ""
Write-Host "To get Sonarr API key (for TV shows):"
Write-Host "1. Go to http://localhost:8989"
Write-Host "2. Settings > General > Security"
Write-Host "3. Copy the API Key value"
Write-Host ""
Write-Host "=== CONTAINER COMMUNICATION ==="
Write-Host "All containers are on the same 'media-stack' network"
Write-Host "Use container hostnames when configuring connections:"
Write-Host "• radarr:7878 (for movies)"
Write-Host "• sonarr:8989 (for TV shows)"
Write-Host ""
Write-Host "=== RECOMMENDED SETTINGS ==="
Write-Host "For best results in Bazarr:"
Write-Host "• Enable 'Search for missing subtitles' scheduler"
Write-Host "• Set subtitle score threshold (e.g., 90%)"
Write-Host "• Enable 'Upgrade previously downloaded subtitles'"
Write-Host "• Configure anti-captcha service for better provider access" 