# Prowlarr Docker Container Setup - Indexer Manager for Radarr
# This script sets up Prowlarr to manage indexers and automatically sync them to Radarr

# IMPORTANT: Update the host paths below to match your actual directories
$hostConfigPath = "C:\docker\prowlarr\config"  # Change this to your preferred config path

# Create a custom Docker network for container communication (if it doesn't exist)
Write-Host "Creating Docker network 'media-stack'..."
cmd /c "docker network create media-stack 2>nul || echo Network already exists"

# Run Prowlarr container on the custom network
cmd /c "docker run --name prowlarr --restart unless-stopped --network media-stack -d -p 9696:9696 -v ${hostConfigPath}:/config ghcr.io/hotio/prowlarr"

Write-Host "=== PROWLARR DOCKER SETUP ==="
Write-Host "Prowlarr container should now be running. Access it at http://localhost:9696"
Write-Host ""
Write-Host "=== PROWLARR CONFIGURATION ==="
Write-Host "1. Access Prowlarr at http://localhost:9696"
Write-Host "2. Go to Settings > Apps to connect to your *arr applications"
Write-Host "3. Add Radarr (Movies):"
Write-Host "   • Name: Radarr"
Write-Host "   • Sync Level: Full Sync"
Write-Host "   • Server: http://radarr:7878"
Write-Host "   • API Key: [Get this from Radarr Settings > General]"
Write-Host "4. Add Sonarr (TV Shows) - if you have it:"
Write-Host "   • Name: Sonarr"
Write-Host "   • Sync Level: Full Sync"
Write-Host "   • Server: http://sonarr:8989"
Write-Host "   • API Key: [Get this from Sonarr Settings > General]"
Write-Host ""
Write-Host "=== ADDING INDEXERS ==="
Write-Host "1. Go to Indexers tab in Prowlarr"
Write-Host "2. Click '+' to add indexers"
Write-Host "3. Popular free options:"
Write-Host "   • YTS (Movies)"
Write-Host "   • EZTV (TV)"
Write-Host "   • TorrentGalaxy"
Write-Host "   • 1337x"
Write-Host "4. For each indexer, ensure 'Enable' is checked"
Write-Host ""
Write-Host "=== AUTOMATIC SYNC ==="
Write-Host "Once configured, Prowlarr will automatically:"
Write-Host "• Add all enabled indexers to Radarr"
Write-Host "• Keep indexer settings synchronized"
Write-Host "• Test indexer connectivity"
Write-Host ""
Write-Host "=== GET RADARR API KEY ==="
Write-Host "To get Radarr API key:"
Write-Host "1. Go to http://localhost:7878"
Write-Host "2. Settings > General"
Write-Host "3. Copy the API Key value"
Write-Host "4. Use this key when adding Radarr app in Prowlarr"
Write-Host ""
Write-Host "=== CONTAINER COMMUNICATION ==="
Write-Host "Prowlarr and Radarr are on the same 'media-stack' network"
Write-Host "Use 'radarr' as hostname when configuring the connection!"
Write-Host ""
Write-Host "=== TESTING ==="
Write-Host "After setup, test in Radarr:"
Write-Host "1. Go to Settings > Indexers in Radarr"
Write-Host "2. You should see indexers automatically added by Prowlarr"
Write-Host "3. Test search functionality"
Write-Host ""
Write-Host "=== COMPLETE YOUR MEDIA STACK ==="
Write-Host "Set up the remaining components:"
Write-Host "• TV Shows: .\run-sonarr.ps1"
Write-Host "• Subtitles: .\run-bazarr.ps1"
Write-Host "Complete stack: Radarr + Sonarr + Prowlarr + Bazarr + Download Client" 